# Generated by Django 6.0.6 on 2026-09-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('decade', models.CharField(max_length=5)),
                ('time', models.TimeField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('shape', models.CharField(max_length=150)),
                ('summary', models.CharField(max_length=150)),
                ('media', models.CharField(max_length=1)),
                ('link', models.URLField()),
            ],
        ),
    ]
